- name: Install redis
  become: true
  apt:
    name: redis-server
    state: present

- name: upload systemd service to server
  become: true
  ansible.builtin.template:
    src: ../files/redis.conf
    dest: /etc/redis/redis.conf
  register: override

- name: stop redis
  become: true
  systemd:
    name: redis-server
    state: stopped
    enabled: yes
  when: override.changed

- name: start redis
  become: true
  systemd:
    name: redis-server
    state: started
    daemon_reload: yes
    enabled: yes
