- hosts: all
  become: true
  roles:
    - base
    - redis
    - nodejs

- hosts: web
  become: true
  roles:
    - deploy
  vars:
    http_port: "{{ http_port }}"
    redis_hostname: "{{ hostvars[groups['redis'][0]]['redis_hostname'] }}"
    database_host: "database_host"
    database_port: "database_port"
    database_name: "database_name"
    username: "username"
    encrypted_password: "password"

#   tasks:
#     - name: Upload Systemd service file
#       copy:
#         src: /path/to/my-awesome-app.service
#         dest: /etc/systemd/system/my-awesome-app.service
#       notify: Reload systemd

# - hosts: all
#   handlers:
#     - name: Reload systemd
#       systemd:
#         daemon_reload: yes
#         state: restarted
#         name: my-awesome-app.service

# - hosts: redis
#   become: true
#   tasks:
#     - name: Print encrypted password
#       copy:
#         content: "{{ encrypted_password }}"
#         dest: /tmp/octoleak.txt
