- name: create worker directory for ansible
  file:
    path: "{{ app_path }}"
    state: directory
    mode: 0755
  become: true

- name: extract worker.tar to worker directory
  unarchive:
    src: "{{ app_path }}/worker.tar"
    dest: "{{ app_path }}"
    remote_src: yes
  become: true

- name: Uploads worker service
  copy:
    src: worker.service
    dest: /etc/systemd/system/worker.service
    mode: 0644
  become: true

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - java-21-openjdk
    - maven

- name: build worker using Maven
  shell: "cd {{ app_path }}/worker && mvn clean install"
  become: true

- name: run worker using systemd
  systemd:
    name: worker
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
