- name: create directory for poll application
  ansible.builtin.file:
    path: /var/www/poll
    state: directory
    owner: www-data
    group: www-data

- name: Extract poll application
  ansible.builtin.unarchive:
    src: poll.tar
    dest: /var/www/poll
    owner: www-data
    group: www-data

- name: Install Python venv package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-venv
    - acl

- name: Create a virtual environment
  become_user: www-data
  ansible.builtin.command:
    cmd: python3 -m venv /var/www/poll/venv
  args:
    creates: /var/www/poll/venv

- name: Install Python dependencies
  become_user: www-data
  ansible.builtin.pip:
    requirements: /var/www/poll/requirements.txt
    virtualenv: /var/www/poll/venv

- name: Upload systemd service file
  ansible.builtin.copy:
    src: ../files/poll.service
    dest: /etc/systemd/system/poll.service

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /etc/systemd/system/poll.service
    owner: root
    group: root
    mode: '0755'

- name: Set REDIS_HOST environment variable in .env file
  ansible.builtin.lineinfile:
    path: /var/www/poll/.env
    line: "REDIS_HOST={{ hostvars['redis']['ansible_all_ipv4_addresses'][0] }}"
    create: yes
    state: present
  

- name: Ensure service is enabled and running
  ansible.builtin.systemd:
    name: poll.service
    state: started
    daemon_reload: true
    enabled: true